### ISSUE TITLE
Empty test run page when upgrading codeceptui from 0.2.1->0.2.2

### ISSUE THREAD

**Issue by nkrishna79** [codecept-js/ui#37]
#### What are you trying to achieve?
Trying to run npx codecept-ui 

#### What do you get instead?
The test run screen is empty. See screenshot below for console errors 

### Environment info

- Windows 10 x64bit
- codeceptjs v2.3.6
- @codecept/ui v0.2.2

![image](https://user-images.githubusercontent.com/37705580/70441237-eac86780-1a8b-11ea-85ce-952dadb6a500.png)

![image](https://user-images.githubusercontent.com/37705580/70441307-0f244400-1a8c-11ea-881f-1f111cdd5d95.png)

**Comment by DavertMik** [comment]
Just released 0.2.3.
@nkrishna79 please check, maybe it is fixed

**Comment by nkrishna79** [comment]
@DavertMik  unfortunately not. still the same issue 
![image](https://user-images.githubusercontent.com/37705580/70628170-8fc77980-1c1f-11ea-927c-75aa52a3a136.png)

**Comment by nkrishna79** [comment]
this is now fixed in v0.2.5. Closed
